theme = "nimble"

[editor]
mouse = false
cursorline = true
true-color = true
color-modes = true
auto-format = true
bufferline = "multiple"
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true
wrap-indicator = "↩ "

[editor.indent-guides]
render = true
character = ""

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[editor.lsp]
display-messages = true
auto-signature-help = true

[keys.normal]
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = [
    "extend_to_line_bounds",
    "delete_selection",
    "move_line_up",
    "paste_before",
]
A-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-up = [
    "extend_to_line_bounds",
    "delete_selection",
    "move_line_up",
    "paste_before",
]

[keys.select]
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]
